#pragma once

#define ASSET_DIRECTORY "assets/"
#define ANIMATION_DIRECTORY ASSET_DIRECTORY"Animations/"
#define MODEL_DIRECTORY ASSET_DIRECTORY"Models/"
#define CHARACTER_DIRECTORY ASSET_DIRECTORY"Characters/"
#define SHADER_DIRECTORY ASSET_DIRECTORY"Shaders/"
#define TEXTURE_DIRECTORY ASSET_DIRECTORY"Textures/"
#define SCENE_DIRECTORY ASSET_DIRECTORY"Scenes/"
#define MAP_DIRECTORY ASSET_DIRECTORY"Maps/"
#define TRANSPARENCY_NONE 0
#define TRANSPARENCY_PARTIAL 1
#define TRANSPARENCY_FULL 2